<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="dataSourceStorageLocal" created-in="PY-241.14494.241">
    <data-source name="usuarios" uuid="9dfde0ce-b229-48f5-8641-976ab166b3a9">
      <database-info product="" version="" jdbc-version="" driver-name="" driver-version="" dbms="SQLITE" />
      <schema-mapping />
    </data-source>
    <data-source name="usuarios [2]" uuid="fdaa0462-35bb-4a11-b87b-cff6d121e4c2">
      <database-info product="SQLite" version="3.45.1" jdbc-version="4.2" driver-name="SQLite JDBC" driver-version="3.45.1.0" dbms="SQLITE" exact-version="3.45.1" exact-driver-version="3.45">
        <identifier-quote-string>&quot;</identifier-quote-string>
      </database-info>
      <case-sensitivity plain-identifiers="mixed" quoted-identifiers="mixed" />
      <auth-provider>no-auth</auth-provider>
      <schema-mapping>
        <introspection-scope>
          <node kind="schema" qname="@" />
        </introspection-scope>
      </schema-mapping>
    </data-source>
  </component>
</project>